// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd-0dBkSkijLgs-nBMuTBctwaCujUGqfY',
    appId: '1:61848603918:web:8ef8a68b9c4261c0f71b5f',
    messagingSenderId: '61848603918',
    projectId: 'attandencetrac',
    authDomain: 'attandencetrac.firebaseapp.com',
    storageBucket: 'attandencetrac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdWbeb_3HYsog53fSaRwCKLhj2thDUYkg',
    appId: '1:61848603918:android:f280f198b43dd07af71b5f',
    messagingSenderId: '61848603918',
    projectId: 'attandencetrac',
    storageBucket: 'attandencetrac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASbj_2zCh3r7Pd58dmMlRy1EMdbvpyKAg',
    appId: '1:61848603918:ios:8a43c899aa7bd218f71b5f',
    messagingSenderId: '61848603918',
    projectId: 'attandencetrac',
    storageBucket: 'attandencetrac.appspot.com',
    iosBundleId: 'com.example.attendenceTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASbj_2zCh3r7Pd58dmMlRy1EMdbvpyKAg',
    appId: '1:61848603918:ios:796a7ebaf8931f24f71b5f',
    messagingSenderId: '61848603918',
    projectId: 'attandencetrac',
    storageBucket: 'attandencetrac.appspot.com',
    iosBundleId: 'com.example.attendenceTrackingApp.RunnerTests',
  );
}
